services:
  oauth_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P4ssw0rd!
      TZ: America/Montevideo
    volumes:
        - .db:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    networks:
        - api-oauth

  oauth_db.configurator:
    image: mcr.microsoft.com/mssql/server:2019-latest
    depends_on:
      oauth_db:
        condition: service_healthy
    environment:
      SA_PASSWORD: P4ssw0rd!
      DB_NAME: laravel
    networks:
        - api-oauth
    command: |
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S oauth_db -U sa -P $${SA_PASSWORD} -C -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = \"$${DB_NAME}\") BEGIN CREATE DATABASE $${DB_NAME} END " || exit
      '

  oauth_php-fpm:
    build: docker/php-fpm
    depends_on:
        oauth_db.configurator:
            condition: service_completed_successfully
    environment:
        SKIP_SEEDERS: true
    networks:
        - api-oauth
    volumes:
        - ./:/var/www/html

  oauth_apache:
    build:
      context: docker/apache
      args:
         PHP_FPM_URL: "oauth_php-fpm"
    ports:
      - "8001:80"
    networks:
        - intranet
        - api-oauth
    volumes:
      - ./public:/var/www/html/public

networks:
  intranet:
    driver: bridge
  api-oauth:
    driver: bridge
