apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  namespace: api-oauth-obligatorio-tecredsw
spec:
  selector:
    matchLabels:
      app: php-fpm
  replicas: 1
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
        - name: php-fpm
          image: desmoris/php-fpm-oauth-obligatorio-tecredsw-2025
          ports:
            - containerPort: 9000
          env:
            - name: SKIP_SEEDERS
              value: "true"
            - name: REPO_URL
              value: "https://github.com/DamianEsmoris/obligatorio-tecredsw-2025_api-oauth"
            - name: DB_CONNECTION
              value: "sqlsrv"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "1433"
            - name: DB_DATABASE
              value: "laravel"
            - name: DB_USERNAME
              value: "sa"
            - name: DB_TRUST_SERVER_CERTIFICATE
              value: "true"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlsrv
                  key: password
